#在application.properties/或者application.yml文件中没有添加数据库配置信息.\
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 20040309cjj
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
#  mvc:
#    static-path-pattern=/static/**:
server:
  port: 80
mybatis:
  type-aliases-package: com.weifeng.musicprogram.Model
  mapper-locations: classpath:mappers/*.xml
